DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS PROPERTY;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS OWNER;

CREATE TABLE CUSTOMER
(
  ID  INT PRIMARY KEY,
  NAME VARCHAR(100),
  MAIL VARCHAR(100),
  PASSWORD VARCHAR(100)
);

CREATE TABLE LOCATION (
  ID INT PRIMARY KEY,
  NAME VARCHAR(100)
);

CREATE TABLE OWNER (
  ID INT PRIMARY KEY,
  NAME VARCHAR(100)
);

CREATE TABLE PROPERTY (
  ID  INT PRIMARY KEY,
  ADDRESS VARCHAR(100),
  LOCATION_ID INT,
  OWNER_ID INT,
  FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (ID),
  FOREIGN KEY (OWNER_ID) REFERENCES OWNER (ID)
);

CREATE TABLE BOOKING (
  ID   INT PRIMARY KEY,
  PROPPERTY_ID INT,
  CUSTOMER_ID INT,
  DATE_FROM DATE,
  DATE_TO DATE,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
  FOREIGN KEY (PROPPERTY_ID) REFERENCES PROPERTY (ID)
);

